### ISSUE TITLE
automatically open the build output window after adding a repo

### ISSUE THREAD

**Issue by hojberg** [drip/drip#10]
When adding a new repository, especially from the /repositories/new screen, we need to show the build output for that first build right after clicking the button

**Comment by cmeiklejohn** [comment]
@hojberg can you hit this one next?

**Comment by hojberg** [comment]
on it

**Comment by hojberg** [comment]
fixed in https://github.com/drip/drip/pull/23

**Comment by hojberg** [comment]
pull into master
