### ISSUE TITLE
Build result status is sometimes wrong

### ISSUE THREAD

**Issue by hojberg** [drip/drip#11]
See: https://skitch.com/rhackr/fsk1m/drip-npm-continuous-integration

I realize that it properly returned with an ok status code, but clearly this test wasn't successful :(

**Comment by hojberg** [comment]
Here is another one where the results looks to be successful, but the status code isnt: https://skitch.com/rhackr/fskuq/drip-node.js-continuous-integration

**Comment by hojberg** [comment]
didnt mean to close it :)

**Comment by cmeiklejohn** [comment]
Closing for now since we're not supporting makefile builds anymore.  If this is a problem with npm, we'll reopen.
