### ISSUE TITLE
Build status update

### ISSUE THREAD

**Issue by cmeiklejohn** [drip/drip#20]
If you're watching a build run, you need to be able to see the status icons change when it finishes.

**Comment by hojberg** [comment]
This is already kinda working. It changes from spinner to complete, what doesnt work is changing from pending to spinner

**Comment by cmeiklejohn** [comment]
The spinner needs change, and the PENDING/RUNNING in the upper right needs to change to FAILED.

**Comment by hojberg** [comment]
fixed in: https://github.com/drip/drip/tree/issue20_build_status_update

**Comment by cmeiklejohn** [comment]
Merged.
